version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - "/data/postgres:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "666:80"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
  redis:
    hostname: redis
    image: redis
    command: redis-server --requirepass PLEASE_CHANGE_ME
    ports:
      - "6379:6379"
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS
      - REDIS_HOST
      - REDIS_DB
      - REDIS_PORT
      - REDIS_AUTH
      - REDIS_PASSWORD
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled
      - network.host
      - http.host
    volumes:
      - "/data/elasticsearch:/usr/share/elasticsearch/data"
  elastichq:
    image: elastichq/elasticsearch-hq
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_SCHEME
      - ELASTICSEARCH_HOST
  pgsync:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./runserver.sh
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to elasticsearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - postgres
      - elasticsearch
      - redis
    environment:
      - PG_USER
      - PG_HOST
      - PG_PASSWORD
      - LOG_LEVEL=INFO
      - ELASTICSEARCH_PORT
      - ELASTICSEARCH_SCHEME
      - ELASTICSEARCH_HOST
      - REDIS_HOST
      - REDIS_AUTH
